### ISSUE TITLE
create some sort of IOT intergretion 

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-Server#15]
I need at least some suggestion for connecting to an IOT ecosystem I don' really know where to start, but I think we should make some sort of integration via an account #13, lets have all the ideas

**Comment by notepad104** [comment]
For what purpose do you need the IOT ecosystem ? Can you list down your requirements, so that I can suggest the appropriate place to start with ?

**Comment by FultonBrowne** [comment]
well, stuff like turn off the lights, run my oven, and close the shades. a smart home.

**Comment by FultonBrowne** [comment]
maybe something like this https://smartthings.github.io/
