### ISSUE TITLE
add news orgs to rssmain.kt

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-Server#23]
At this time there are only 2 news sources for each category, that needs to be better. you can change all of the any sources by editing the main string list in rssmain.kt, all the rest is done by my simple algorithm.

**Comment by HalfStackZay** [comment]
Happy to help with this one.

**Comment by FultonBrowne** [comment]
thank you @HalfStackZa I am going to keep this issue, because you can never have enough news sources :-}
